### ISSUE TITLE
Plugin vision

### ISSUE THREAD

**Issue by Buda9** [onbirdev/moodle-enrol_cart#1]
Hi there.

This plugin seems interesting and I'm interested in the future of it. Could you please just share your vision of this plugin? Afterwards, from time to time, I can create PR's.

Thank you

**Comment by onbirdev** [comment]
Hi,

Thank you for your interest in the plugin! My vision for this plugin is to provide a seamless and flexible shopping cart experience for Moodle users, allowing them to easily manage course enrolments and payments. I aim to continuously improve the plugin by adding more features, enhancing user experience, and ensuring compatibility with future Moodle updates.

I appreciate your willingness to contribute, and I'm excited to see your PRs in the future. If you have any ideas or suggestions, feel free to share them!

Thanks again!
