### ISSUE TITLE
Namespace collisions

### ISSUE THREAD

**Issue by volodymyrdovhan** [onbirdev/moodle-enrol_cart#5]
Hello,

According to Moodle standards, all custom classes that are not part of the core API should be placed in the 'classes/local' folder to avoid potential namespace collisions. You can refer to the guidelines here:
[Namespace Collisions - Moodle Plugin Checklist](https://moodledev.io/general/community/plugincontribution/checklist#namespace-collisions)

Additionally, please review the rules for level 2 namespaces:
[Level 2 Namespaces](https://moodledev.io/general/development/policies/codingstyle#rules-for-level2)

![image](https://github.com/user-attachments/assets/b71fd6db-6760-426a-9c25-db265f180992)

**Comment by onbirdev** [comment]
Hello,  
Thank you for the guidance! I have moved the `form`, `formatter`, `helper`, and `object` classes to `classes/local` as recommended. However, the `payment` class is part of the Moodle core API, so I have kept it in its original location.
