### ISSUE TITLE
Moodle cache utilisation

### ISSUE THREAD

**Issue by volodymyrdovhan** [onbirdev/moodle-enrol_cart#8]
Hello,
The plugin uses cookies to store guest cart details. As a recommendation, please consider using Moodle cache with MODE_SESSION mode.

More details: https://moodledev.io/docs/4.5/apis/subsystems/muc
https://docs.moodle.org/dev/Cache_API_-_Quick_reference#:~:text=(cache_store%3A%3A-,MODE_SESSION,-%2C%20%27component%27

![image](https://github.com/user-attachments/assets/d95f50fc-5284-4292-ad03-43c33560a62e)

**Comment by onbirdev** [comment]
Hello,

Thank you for your suggestion. Using cookies lets us keep the cart details for a longer time, even after the browser is closed. But if we use MODE_SESSION in Moodle cache, the cart will be cleared as soon as the user closes their browser.
