### ISSUE TITLE
Capabilities validation improvements

### ISSUE THREAD

**Issue by volodymyrdovhan** [onbirdev/moodle-enrol_cart#9]
Hello,
please consider capabilities validation improvements. In some files missing any capabilities validation, including it on each file/action is recommended.

You can validate capabilities for guests with Force guest login enabled and this will allow to use standard Moodle guest role and capabilities validation.
If you don't need to Force user to login, then please consider adding capabilities validation at least for logged-in users.

![image](https://github.com/user-attachments/assets/f496d60b-a370-476d-9325-b4421364286a)

**Comment by onbirdev** [comment]
Hello,
I have added capability validation for logged-in users as recommended.
